title: My_site
description: asd
template:
  repo: my_site-template
  name: my_site
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
